### ISSUE TITLE
Some small points?!

### ISSUE THREAD

**Issue by sevamoo** [awjuliani/Pix2Pix-Film#1]
Hi 
Thanks a lot for putting all this together and thanks for your great blog posts on Medium. 
Seems there are some small issues with some variables, if I am not wrong. Can you please, check variables such as imagesS and dataS in the section of training the network?
Thanks a lot.
Best
Vahid

**Comment by awjuliani** [comment]
Thanks for pointing these out! I had gone through and renamed some of the variables and cleaned up the code, but I missed those. It should all be consistent now.
