### ISSUE TITLE
Update required to run on Tensorflow 1.0

### ISSUE THREAD

**Issue by kieran-mace** [awjuliani/Pix2Pix-Film#4]
When running the python notebook, I get an error that is associated with tf.concat(3,[gen0,enc2])

It seems like the order of the arguments should now be flipped to tf.concat([gen0,enc2],3)

I can create a PR if you're interested in porting this code over to TF 1.0

**Comment by awjuliani** [comment]
Hi Kieran,

Thanks for pointing this out! Just fixed the syntax in the notebook.
